### ISSUE TITLE
pyopenms DLL issue

### ISSUE THREAD

**Issue by AUldry** [compomics/ms2rescore#149]
Dear all,

I'm downloaded and installed MS2Rescore-v3.0.3-Windows64bit.exe on our Windows 10 Enterprise server. It installs without issues, but we get the following message when the program starts:

---------------------------------------------
Traceback (most recent call last):
  File "ms2rescore\gui\__main__.py", line 7, in <module>
    from ms2rescore.gui.app import app
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ms2rescore\__init__.py", line 16, in <module>
    from ms2rescore.core import rescore  # noqa: F401 E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ms2rescore\core.py", line 6, in <module>
    import psm_utils.io
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "psm_utils\io\__init__.py", line 11, in <module>
    import psm_utils.io.idxml as idxml
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "psm_utils\io\idxml.py", line 33, in <module>
    import pyopenms as oms  #noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pyopenms\__init__.py", line 107, in <module>
  File "pyopenms\__init__.py", line 65, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pyopenms\_all_modules.py", line 1, in <module>
ImportError: DLL load failed while importing _pyopenms_1: A dynamic link library (DLL) initialization routine failed.
----------------------------------------------------

I'm a little hazy as to whether this windows executable comes with python stuff all packaged in, or whether it's trying to use our pre-installed python install. We do have indeed python 3.9, there, and pyopenms 3.0.0. Import pyopenms does not complain when invoked.

Any idea what is to be done? Thanks in advance!

Best wishes,

**Comment by RalfG** [comment]
Hi @AUldry,

Thanks for posting an issue. The Windows installer packages everything it needs and does not use any externally installed Python libraries. I do not expect the preinstalled pyOpenMS to be an issue, but you never know.

Could you retry with MS²Rescore v3.1.0?

If the issue persists, you could also try to install ms2rescore in the command line with `pip install ms2rescore` and then start the GUI application with the command `ms2rescore-gui`. If the issue is also occurs there, there might be an incompatibility between OpenMS and something else on your system. In that case, the OpenMS team might be able to help out.

Thanks!
Ralf
