### ISSUE TITLE
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: NotCentroided

### ISSUE THREAD

**Issue by frankligy** [compomics/ms2rescore#193]
Hello,

Thanks for the great tool, I am using MaxQuant and had been successfully running through a few datasets, but this time, when applied to a new dataset, it got stalled in the MS2PIP feature generating steps and the error doesn't immediately makes sense to me in terms of how to solve, is it a occasional glitch on how msConvert performs when it converts raw to mzml and leave some spectrum not compliant with the way MS2pip read it? 

```python
ms2pip_fgen = MS2PIPFeatureGenerator(
    model="Immuno-HCD",
    ms2_tolerance=0.02,
    spectrum_path=spectrum_dir,
    spectrum_id_pattern=r".*scan=(\d+)$",
    processes=1,
)

ms2pip_fgen.add_features(psm_list)
```

'''bash
thread '<unnamed>' panicked at src/parse_mzdata.rs:39:65:
called `Result::unwrap()` on an `Err` value: NotCentroided
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/gpfs/data/yarmarkovichlab/Frank/pan_cancer/rescore/ms2rescore_new_env/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/gpfs/data/yarmarkovichlab/Frank/pan_cancer/rescore/ms2rescore_new_env/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/data/yarmarkovichlab/Frank/pan_cancer/rescore/ms2rescore_new_env/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/gpfs/data/yarmarkovichlab/Frank/pan_cancer/rescore/ms2rescore_new_env/lib/python3.9/site-packages/ms2pip/core.py", line 868, in _process_spectra
    for spectrum in read_spectrum_file(spec_file):
  File "/gpfs/data/yarmarkovichlab/Frank/pan_cancer/rescore/ms2rescore_new_env/lib/python3.9/site-packages/ms2pip/spectrum_input.py", line 36, in read_spectrum_file
    for spectrum in get_ms2_spectra(str(spectrum_file)):
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: NotCentroided
'''

**Comment by RalfG** [comment]
Hi Frank,

Could it be that the mzML file was converted in MSConvert without any peak picking option enabled? Peak picking should be in the "filter" list, as in this screenshot (here for MGF, but should be the same for mzML).

![image](https://github.com/user-attachments/assets/f01c787e-edb6-418c-92f4-7143397d1626)

Let us know if this was indeed the issue or not.

Thanks!
Ralf

**Comment by frankligy** [comment]
thank you for the clarifications!
