### ISSUE TITLE
MaxQuant can have long-format modification notations; does not work in current implementation

### ISSUE THREAD

**Issue by NoeGuilloy** [compomics/ms2rescore#41]
Hi,

I am running ms2pip through ms2resocre, and i get that following  Index  error.

Merging results
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/noeguill/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/noeguill/anaconda3/lib/python3.7/site-packages/ms2pip/ms2pipC.py", line 316, in process_spectra
    modpeptide = apply_mods(peptide, mods, PTMmap)
  File "/home/noeguill/anaconda3/lib/python3.7/site-packages/ms2pip/ms2pipC.py", line 631, in apply_mods
    modpeptide[pos] = mod
IndexError: index 23 is out of bounds for axis 0 with size 19
"""

Any ideas ?

Thanks a lot,
Noé

**Comment by RalfG** [comment]
Hi @NoeGuilloy, 

As of [v2.1.1](https://github.com/compomics/ms2rescore/releases/tag/v2.1.1), we now support the long-format modification labels in MaxQuant msms.txt files. Let us know if you would experience other issues.

Best,
Ralf
