### ISSUE TITLE
Not able to run ms2resore through command line for this repo examples

### ISSUE THREAD

**Issue by rolivella** [compomics/ms2rescore#89]
Hello

I'm trying to run ms2rescore through the command line with the example dataset available at the ms2rescore repo: 

MGF file: https://github.com/compomics/ms2rescore/blob/master/examples/mgf/20161213_NGHF_DBJ_SA_Exp3A_HeLa_1ug_7min_15000_02.mgf.zip

MZID file: https://github.com/compomics/ms2rescore/blob/master/examples/id/msgfplus.mzid

And this config file: [config.zip](https://github.com/compomics/ms2rescore/files/11958222/config.zip)

If run it on Ubuntu 22.04 through this command: 
`ms2rescore -c config.json -m 20161213_NGHF_DBJ_SA_Exp3A_HeLa_1ug_7min_15000_02.mgf msgfplus.mzid`

I get this error. Am I missing some file? Thanks. 

```
2023-07-04 14:37:49 // INFO // ms2rescore // Using MSGFPipeline.
2023-07-04 14:37:49 // INFO // ms2rescore.percolator // Running Percolator PIN converter

Pin-converter version 3.06.1, Build Date Jun 15 2023 14:57:04
Copyright (c) 2013 Lukas Käll. All rights reserved.
Written by Lukas Käll (lukas.kall@scilifelab.se) in the
School of Biotechnology at KTH - Royal Institute of Technology, Stockholm.
Issued command:
msgf2pin -P XXX -o /tmp/tmp3sn1zv2g/20161213_NGHF_DBJ_SA_Exp3A_HeLa_1ug_7min_15000_02_original.pin /home/proteomics/mysoftware/compomics/mgf/20161213_NGHF_DBJ_SA_Exp3A_HeLa_1ug_7min_15000_02.mzid

Uses features for fragment spectra mass errors
Reading /home/proteomics/mysoftware/compomics/mgf/20161213_NGHF_DBJ_SA_Exp3A_HeLa_1ug_7min_15000_02.mzid
No scan number was found for a PSM (or it equaled 0), scans are ranked from 1 and up
2023-07-04 14:38:01 // ERROR // ms2rescore.__main__ // Critical error occured in MS2ReScore
Traceback (most recent call last):
  File "/home/proteomics/.local/lib/python3.10/site-packages/ms2rescore/__main__.py", line 15, in main
    rescore.run()
  File "/home/proteomics/.local/lib/python3.10/site-packages/ms2rescore/__init__.py", line 233, in run
    peprec = self.pipeline.get_peprec()
  File "/home/proteomics/.local/lib/python3.10/site-packages/ms2rescore/id_file_parser.py", line 245, in get_peprec
    return self.peprec_from_pin()
  File "/home/proteomics/.local/lib/python3.10/site-packages/ms2rescore/id_file_parser.py", line 191, in peprec_from_pin
    raise IDFileParserError(
ms2rescore.id_file_parser.IDFileParserError: Could not map all MGF retention times to spectrum indices.
```

**Comment by rolivella** [comment]
Hello again, I've just reviewed my own issue and I'm a little closer to the solution. I understand from the documentation: 

https://ms2rescore.readthedocs.io/en/latest/userguide/configuration/#mapping-psms-to-spectra

That I should add something like this to the JSON config file: 

```json
"spectrum_id_pattern": ".*scan=(\\d+)$",
"psm_id_pattern": ".*\\..*\\.(.*)"
```

However, in my `mzid` file there's no any `spectrum_id` field, so how can I parse the PSM with the `psm_id_pattern`? 

Thanks!

**Comment by rolivella** [comment]
I modified the JSON config file with the correct regex and does not work: 
* regex for the MGF file: https://regex101.com/r/VhBJRM/1
* regex for the mzID file: https://regex101.com/r/YWPevL/1

**Comment by RalfG** [comment]
Hi @widmersimon,

Could you retry with MS²Rescore the latest beta version of MS²Rescore 3.0? You can install it with:

```sh
pip install ms2rescore --pre
```

Matching IDs from the PSM file to the spectrum files is always a bit tricky, as their is no single solution. We tried to streamline the process with v3.0.

Let us know if the issue persists and we'll gladly help you out!

**Comment by rolivella** [comment]
@RalfG thanks! I'll try it and let you know!

**Comment by rolivella** [comment]
@RalfG I cannot upgrade to beta. I get this: 

```bash
proteomics@hipnos6:~/mysoftware/compomics$ pip install ms2rescore --pre
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ms2rescore in /home/proteomics/.local/lib/python3.10/site-packages (2.1.3)
Requirement already satisfied: scikit-learn<2,>=0.20.0 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (1.2.2)
Requirement already satisfied: pyteomics<5,>=4.1.0 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (4.6)
Requirement already satisfied: matplotlib<4,>=3 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (3.7.1)
Requirement already satisfied: statsmodels>=0.12 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (0.14.0)
Requirement already satisfied: lxml<5,>=4.5 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (4.9.2)
Requirement already satisfied: cascade-config<2,>=0.3.0 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (0.3.0)
Requirement already satisfied: click<8,>=7 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (7.1.2)
Requirement already satisfied: tqdm<5,>=4.31.0 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (4.65.0)
Requirement already satisfied: numpy<2,>=1.16.0 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (1.24.3)
Requirement already satisfied: seaborn>=0.11 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (0.12.2)
Requirement already satisfied: ms2pip<4,>=3.8 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (3.11.0)
Requirement already satisfied: scipy<2,>=1.2.0 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (1.11.0)
Requirement already satisfied: deeplc>=0.1.17 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (2.2.2)
Requirement already satisfied: pandas<2,>=0.24.0 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2rescore) (1.5.3)
Requirement already satisfied: jsonschema<4,>=3 in /usr/lib/python3/dist-packages (from cascade-config<2,>=0.3.0->ms2rescore) (3.2.0)
Requirement already satisfied: tensorflow<3,>=2.2 in /home/proteomics/.local/lib/python3.10/site-packages (from deeplc>=0.1.17->ms2rescore) (2.11.1)
Requirement already satisfied: setuptools>=42.0.1 in /usr/lib/python3/dist-packages (from deeplc>=0.1.17->ms2rescore) (59.6.0)
Requirement already satisfied: pygam<1,>=0.8.0 in /home/proteomics/.local/lib/python3.10/site-packages (from deeplc>=0.1.17->ms2rescore) (0.9.0)
Requirement already satisfied: psm-utils<1,>=0.2.3 in /home/proteomics/.local/lib/python3.10/site-packages (from deeplc>=0.1.17->ms2rescore) (0.3.1)
Requirement already satisfied: hdf5plugin>=4.1.1 in /home/proteomics/.local/lib/python3.10/site-packages (from deeplc>=0.1.17->ms2rescore) (4.1.3)
Requirement already satisfied: h5py<4,>=2.10.0 in /home/proteomics/.local/lib/python3.10/site-packages (from deeplc>=0.1.17->ms2rescore) (3.9.0)
Requirement already satisfied: deeplcretrainer<1,>=0.1 in /home/proteomics/.local/lib/python3.10/site-packages (from deeplc>=0.1.17->ms2rescore) (0.1.17)
Requirement already satisfied: cycler>=0.10 in /home/proteomics/.local/lib/python3.10/site-packages (from matplotlib<4,>=3->ms2rescore) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3/dist-packages (from matplotlib<4,>=3->ms2rescore) (2.8.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/proteomics/.local/lib/python3.10/site-packages (from matplotlib<4,>=3->ms2rescore) (4.40.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib<4,>=3->ms2rescore) (9.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/proteomics/.local/lib/python3.10/site-packages (from matplotlib<4,>=3->ms2rescore) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib<4,>=3->ms2rescore) (2.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3/dist-packages (from matplotlib<4,>=3->ms2rescore) (21.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/proteomics/.local/lib/python3.10/site-packages (from matplotlib<4,>=3->ms2rescore) (1.1.0)
Requirement already satisfied: tables>=3.4 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2pip<4,>=3.8->ms2rescore) (3.8.0)
Requirement already satisfied: pydantic<2,>=1.10 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2pip<4,>=3.8->ms2rescore) (1.10.9)
Requirement already satisfied: tomlkit<1,>=0.5 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2pip<4,>=3.8->ms2rescore) (0.11.8)
Requirement already satisfied: xgboost<2,>=1.3 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2pip<4,>=3.8->ms2rescore) (1.7.6)
Requirement already satisfied: sqlalchemy<2,>=1.3 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2pip<4,>=3.8->ms2rescore) (1.4.48)
Requirement already satisfied: biopython<2,>=1.74 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2pip<4,>=3.8->ms2rescore) (1.81)
Requirement already satisfied: spectrum-utils==0.3.5 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2pip<4,>=3.8->ms2rescore) (0.3.5)
Requirement already satisfied: rich>=13 in /home/proteomics/.local/lib/python3.10/site-packages (from ms2pip<4,>=3.8->ms2rescore) (13.4.2)
Requirement already satisfied: numba>=0.47 in /home/proteomics/.local/lib/python3.10/site-packages (from spectrum-utils==0.3.5->ms2pip<4,>=3.8->ms2rescore) (0.57.1)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas<2,>=0.24.0->ms2rescore) (2022.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/proteomics/.local/lib/python3.10/site-packages (from scikit-learn<2,>=0.20.0->ms2rescore) (3.1.0)
Requirement already satisfied: joblib>=1.1.1 in /home/proteomics/.local/lib/python3.10/site-packages (from scikit-learn<2,>=0.20.0->ms2rescore) (1.2.0)
Requirement already satisfied: patsy>=0.5.2 in /home/proteomics/.local/lib/python3.10/site-packages (from statsmodels>=0.12->ms2rescore) (0.5.3)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from patsy>=0.5.2->statsmodels>=0.12->ms2rescore) (1.16.0)
Requirement already satisfied: psims in /home/proteomics/.local/lib/python3.10/site-packages (from psm-utils<1,>=0.2.3->deeplc>=0.1.17->ms2rescore) (1.2.5)
Requirement already satisfied: typing-extensions>=4.2.0 in /home/proteomics/.local/lib/python3.10/site-packages (from pydantic<2,>=1.10->ms2pip<4,>=3.8->ms2rescore) (4.6.3)
Requirement already satisfied: progressbar2<5.0.0,>=4.2.0 in /home/proteomics/.local/lib/python3.10/site-packages (from pygam<1,>=0.8.0->deeplc>=0.1.17->ms2rescore) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/proteomics/.local/lib/python3.10/site-packages (from rich>=13->ms2pip<4,>=3.8->ms2rescore) (2.15.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/proteomics/.local/lib/python3.10/site-packages (from rich>=13->ms2pip<4,>=3.8->ms2rescore) (3.0.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/lib/python3/dist-packages (from sqlalchemy<2,>=1.3->ms2pip<4,>=3.8->ms2rescore) (1.1.2)
Requirement already satisfied: numexpr>=2.6.2 in /home/proteomics/.local/lib/python3.10/site-packages (from tables>=3.4->ms2pip<4,>=3.8->ms2rescore) (2.8.4)
Requirement already satisfied: py-cpuinfo in /home/proteomics/.local/lib/python3.10/site-packages (from tables>=3.4->ms2pip<4,>=3.8->ms2rescore) (9.0.0)
Requirement already satisfied: blosc2~=2.0.0 in /home/proteomics/.local/lib/python3.10/site-packages (from tables>=3.4->ms2pip<4,>=3.8->ms2rescore) (2.0.0)
Requirement already satisfied: cython>=0.29.21 in /home/proteomics/.local/lib/python3.10/site-packages (from tables>=3.4->ms2pip<4,>=3.8->ms2rescore) (0.29.35)
Requirement already satisfied: flatbuffers>=2.0 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (23.5.26)
Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (2.11.0)
Requirement already satisfied: termcolor>=1.1.0 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (2.3.0)
Requirement already satisfied: keras<2.12,>=2.11.0 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (2.11.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (3.3.0)
Requirement already satisfied: libclang>=13.0.0 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (16.0.0)
Requirement already satisfied: absl-py>=1.0.0 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (1.4.0)
Requirement already satisfied: wrapt>=1.11.0 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (1.15.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (1.56.0)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/lib/python3/dist-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (3.12.4)
Requirement already satisfied: tensorboard<2.12,>=2.11 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (2.11.2)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (0.2.0)
Requirement already satisfied: astunparse>=1.6.0 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (1.6.3)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (0.32.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse>=1.6.0->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (0.37.1)
Requirement already satisfied: msgpack in /usr/lib/python3/dist-packages (from blosc2~=2.0.0->tables>=3.4->ms2pip<4,>=3.8->ms2rescore) (1.0.3)
Requirement already satisfied: mdurl~=0.1 in /home/proteomics/.local/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=13->ms2pip<4,>=3.8->ms2rescore) (0.1.2)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in /home/proteomics/.local/lib/python3.10/site-packages (from numba>=0.47->spectrum-utils==0.3.5->ms2pip<4,>=3.8->ms2rescore) (0.40.1)
Requirement already satisfied: python-utils>=3.0.0 in /home/proteomics/.local/lib/python3.10/site-packages (from progressbar2<5.0.0,>=4.2.0->pygam<1,>=0.8.0->deeplc>=0.1.17->ms2rescore) (3.7.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (2.3.6)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (0.6.1)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/lib/python3/dist-packages (from tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (2.25.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (2.20.0)
Requirement already satisfied: markdown>=2.6.8 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (3.4.3)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/proteomics/.local/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (0.4.6)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/proteomics/.local/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/proteomics/.local/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (0.3.0)
Requirement already satisfied: urllib3<2.0 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (1.26.5)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/proteomics/.local/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/proteomics/.local/lib/python3.10/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in /home/proteomics/.local/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (2.1.3)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/proteomics/.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow<3,>=2.2->deeplc>=0.1.17->ms2rescore) (3.2.0)
proteomics@hipnos6:~/mysoftware/compomics$ ms2rescore -v
2.1.3
```

**Comment by rolivella** [comment]
@RalfG works like a charm! Thank you very much

**Comment by RalfG** [comment]
That's great to hear! Thank you so much for the update!
